### ISSUE TITLE
Vulnerability to absence of retiring r-spatial packages

### ISSUE THREAD

**Issue by rsbivand** [brry/OSMscale#1]
[00check.log](https://github.com/brry/OSMscale/files/11141129/00check.log)
[00install.out.txt](https://github.com/brry/OSMscale/files/11141130/00install.out.txt)
is a recent check log from running under `_SP_EVOLUTION_STATUS_=2` without retiring r-spatial packages (suggested in this package) on the library path. The minimal correction is to check that the package namespaces can be loaded, and if not, do not run those parts of the examples. It would be safer in the longer term to replace retiring r-spatial packages with active r-spatial/rspatial packages (see https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). The specific problem should be resolved by https://github.com/ifellows/ROSM/issues/15 when it feeds through.

**Comment by brry** [comment]
Thank you so much for all your work in the spatial transition!

The last commit to `OpenStreetMap` (as referenced above) was 4 years ago.  
Shoud I try to move the core code to [rosm](https://github.com/paleolimbot/rosm)? Note this is diffferent from the ROSM above.  
Since [2019](https://github.com/paleolimbot/rosm/commit/0607a5d7c5f4c1b36fef11af893162aae279be2a#diff-72778b58969c8ca8268402860b0e003e3d213a26c812bc9f9b928395c284c99fR35), `rosm` is expected to retire "next year", so I'm not sure if it's worth it..

What is currently the best option for quick static maps with an OSM background?

**Comment by rsbivand** [comment]
I am not sure what now matches best, since interactive mapping has taken over a good deal of the activity in those kinds of tasks. I use `mapview` or `tmap` and take a screenshot for record (can be scripted); `ggmap` is also a possibility though I don't use it. `OpenStreetMap` as you say has not been changed for some time - the issue there is 4 months old with no reaction. Perhaps the underlying technology has outlived its usefulness?

**Comment by rsbivand** [comment]
I asked the maintainer of `loa` to collaborate too, but it may be sensible to work around `OpenStreetMap`.

**Comment by brry** [comment]
The maintainer of `OpenStreetMap` confirmed in private communication that he will adapt his dependencies before the deadline.  
For now, I therefore do not plan changes in this package.

**Comment by rsbivand** [comment]
@brry https://github.com/ifellows/ROSM/issues/15 has not yet been resolved, I'm afraid. Could you please either work around or help in getting the update to CRAN in time?

**Comment by brry** [comment]
I will look at using rosm instead.

**Comment by brry** [comment]
It looks like I will use [maptiles](https://github.com/riatelab/maptiles/) instead, as loading rosm also triggers the rgdal messages.  I need to at least figure out (i.e. copy from elsewhere) a default zoom value mechanism.

Edit: I loaded an old version of `rosm`, the new version works fine.

**Comment by rsbivand** [comment]
@brry Please submit the new version to CRAN ASAP.

R spatial infrastructure packages maptools, rgdal and rgeos will be archived by CRAN on Monday, October 16, 2023. Your package does not pass CMD check when these packages are not available. Expect your package to be archived by CRAN October 17-18 as CRAN checks feed through and your package fails, if not updated by Monday, October 16, 2023. 

No grace period is anticipated, as you have had sufficient time to update your package to remove dependencies on maptools, rgdal and/or rgeos, or on packages that you import that have not met the deadline.

**Comment by brry** [comment]
Thanks for the update. I have emailed Ian once more. If he doesn't change it in time, I will implement one of the options below.

```r
# data ----

d <- read.table(sep=",", header=TRUE, text=
"lat, long
52.514464, 13.350137
52.370000, 13.120000
55.685143, 12.580008
50.106452, 14.419989
48.847003, 2.3372130
51.505364,-0.1647520")
d <- d[,2:1]
plot(d, asp=1.5, las=1, col="red")
rdwd::addBorders()
d <- d[1:2,] # close up


# OpenStreetMap ----
# nice map, scalebar, projection, uses rJava (OK) - uses rgdal (taken off CRAN soon) !!
dmap <- OSMscale::pointsMap(lat, long, data=d)
zoom <- attr(dmap,"zoom")
 

# maptiles ----
# zoom needs to be automated, bad resolution, no scalebar etc, but could be projected
dsf <- sf::st_as_sf(d, coords=c("long", "lat"), crs=4326)
bounds <- sf::st_bbox(dsf)
maptiles::plot_tiles(maptiles::get_tiles(bounds, crop=T, zoom=zoom, project=FALSE,
                                         cachedir="maptilescache"), adjust=F) 

# rosm ----
# bad resolution, no scalebar etc, but has autozoom (unlike maptiles)
bounds2 <- sf::st_bbox(sf::st_transform(dsf, "EPSG:3857"))
bounds2 <- wk::rct(bounds2$xmin, bounds2$ymin, bounds2$xmax, bounds2$ymax, crs="EPSG:3857")
rmap <- rosm::osm_raster(bounds2, rosm::osm_url_spec(), zoom=zoom)
rmap <- wk::grd_crop(rmap, bounds2)
plot(rmap)


# leaflet screenshot ----
# external image (not within R), no zoom control, no scalebar etc
library(leaflet)
dl <- leaflet(d) %>% addTiles() %>%  addCircles(~long, ~lat) ; dl
mapview::mapshot(dl, file="map.png") ; berryFunctions::openFile("map.png")
```

Edit: I opened issues on resolution at https://github.com/paleolimbot/rosm/issues/30 and https://github.com/riatelab/maptiles/issues/27

**Comment by brry** [comment]
Ian Fellows is updating `OpenStreetMap` - it's already on github and should be on its way to CRAN soon.  

I am also updating `OSMscale` to not need `sp` anymore :)

**Comment by rsbivand** [comment]
@brry OK, thanks!

**Comment by rsbivand** [comment]
Looks OK with OpenStreetMap 0.4.0, thanks for your cooperation!
